


shinyUI(
  dashboardPage(
    dashboardHeader(title = "Tableaux de la conjoncture", titleWidth = 300),
    
    dashboardSidebar(width = 100,
                     sidebarMenu(id = "tabs_menu",
                                 menuItem("Dashboard", tabName = "dashboard", icon = icon("dashboard")),
                                 menuItem("AL",
                                          tabName = "1",
                                          icon = icon("fas fa-sitemap"),
                                          startExpanded = F),
                                 menuItem("BENL",
                                          tabName = "2",
                                          icon = icon("fas fa-sitemap"),
                                          startExpanded = F),
                                 menuItem("CN",
                                          tabName = "3",
                                          icon = icon("fas fa-sitemap"),
                                          startExpanded = F),
                                 menuItem("COMEXT",
                                          tabName = "4",
                                          icon = icon("fas fa-sitemap"),
                                          startExpanded = F),
                                 menuItem("CONSO",
                                          tabName = "5",
                                          icon = icon("fas fa-sitemap"),
                                          startExpanded = F),
                                 menuItem("DM",
                                          tabName = "6",
                                          icon = icon("fas fa-sitemap"),
                                          startExpanded = F),
                                 menuItem("EM",
                                          tabName = "7",
                                          icon = icon("fas fa-sitemap"),
                                          startExpanded = F),
                                 menuItem("EMPL",
                                          tabName = "8",
                                          icon = icon("fas fa-sitemap"),
                                          startExpanded = F),
                                 menuItem("ES",
                                          tabName = "9",
                                          icon = icon("fas fa-sitemap"),
                                          startExpanded = F),
                                 menuItem("FI",
                                          tabName = "10",
                                          icon = icon("fas fa-sitemap"),
                                          startExpanded = F),
                                 menuItem("FITAUX",
                                          tabName = "11",
                                          icon = icon("fas fa-sitemap"),
                                          startExpanded = F),
                                 menuItem("INV",
                                          tabName = "12",
                                          icon = icon("fas fa-sitemap"),
                                          startExpanded = F), 
                                 menuItem("IT",
                                          tabName = "13",
                                          icon = icon("fas fa-sitemap"),
                                          startExpanded = F),
                                 menuItem("JP",
                                          tabName = "14",
                                          icon = icon("fas fa-sitemap"),
                                          startExpanded = F),
                                 menuItem("OIL",
                                          tabName = "15",
                                          icon = icon("fas fa-sitemap"),
                                          startExpanded = F),
                                 menuItem("PIBFR",
                                          tabName = "16",
                                          icon = icon("fas fa-sitemap"),
                                          startExpanded = F),
                                 menuItem("PROD",
                                          tabName = "17",
                                          icon = icon("fas fa-sitemap"),
                                          startExpanded = F),
                                 menuItem("REV",
                                          tabName = "18",
                                          icon = icon("fas fa-sitemap"),
                                          startExpanded = F),
                                 menuItem("SYN",
                                          tabName = "19",
                                          icon = icon("fas fa-sitemap"),
                                          startExpanded = F),
                                 menuItem("UK",
                                          tabName = "20",
                                          icon = icon("fas fa-sitemap"),
                                          startExpanded = F),
                                 menuItem("US",
                                          tabName = "21",
                                          icon = icon("fas fa-sitemap"),
                                          startExpanded = F),
                                 menuItem("ZE",
                                          tabName = "22",
                                          icon = icon("fas fa-sitemap"),
                                          startExpanded = F)
                             
                     )
    ),
    ## Body content
    dashboardBody(
      tabItems(
          
          tabItem(tabName ="1",fluidRow(
            "coucou8"
          )),
          tabItem(tabName ='2',fluidRow(
            box(title = "Tableau", width = 12, solidHeader = TRUE, status = "primary", DT::dataTableOutput("table")),
            box(title = "Graphe", width = 12, solidHeader = TRUE, status = "primary", "Box content")
          )),
          tabItem(tabName ='3',fluidRow(DT::dataTableOutput("table"))),
          tabItem(tabName ='4',fluidRow(DT::dataTableOutput("table"))),
          tabItem(tabName ='5',fluidRow(DT::dataTableOutput("table"))),
          tabItem(tabName ='6',fluidRow(DT::dataTableOutput("table"))),
          tabItem(tabName ='7',fluidRow(DT::dataTableOutput("table"))),
          tabItem(tabName ='8',fluidRow(DT::dataTableOutput("table"))),
          tabItem(tabName ='9',fluidRow(DT::dataTableOutput("table"))),
          tabItem(tabName ='10',fluidRow(DT::dataTableOutput("table"))),
          tabItem(tabName ='11',fluidRow(DT::dataTableOutput("table"))),
          tabItem(tabName ='12',fluidRow(DT::dataTableOutput("table"))),
          tabItem(tabName ='13',fluidRow(DT::dataTableOutput("table"))),
          tabItem(tabName ='14',fluidRow(DT::dataTableOutput("table"))),
          tabItem(tabName ='15',fluidRow(DT::dataTableOutput("table"))),
          tabItem(tabName ='16',fluidRow(DT::dataTableOutput("table"))),
          tabItem(tabName ='17',fluidRow(DT::dataTableOutput("table"))),
          tabItem(tabName ='18',fluidRow(DT::dataTableOutput("table"))),
          tabItem(tabName ='19',fluidRow(DT::dataTableOutput("table"))),
          tabItem(tabName ='20',fluidRow(DT::dataTableOutput("table"))),
          tabItem(tabName ='21',fluidRow(DT::dataTableOutput("table"))),
          tabItem(tabName ='22',fluidRow(DT::dataTableOutput("table")))
      )
    )
  ))


